export enum CacheIds {
	UseCheckinStyles = "UseCheckinStyles",
	CommandDefs = "CommandDefs",
	LatestQuery = "LatestQuery",
	DatabaseOptions = "DatabaseOptions",
	SearchOptions = "SearchOptions",
	ObjectDef = "ObjectDef",
	EnumDetails = "EnumDetails",
	SearchClauses = "SearchClauses",
	SearchFieldClauses = "SearchFieldClauses",
	ViewpanePropDefs = "ViewpanePropDefs",
	Messages = "Messages",
	SuppressDataEntryForm = "SuppressDataEntryForm",
	DefaultRecordType = "DefaultRecordType",
}
