// Copyright(c) Microsoft.All rights reserved.Licensed under the MIT license.See full license at the root of the repo.

// This file provides all the detailed OOXML manipulation. 

using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml;
using System.IO;
using We = DocumentFormat.OpenXml.Office2013.WebExtension;
using Wetp = DocumentFormat.OpenXml.Office2013.WebExtentionPane;
using System;

namespace Office_OOXML_EmbedAddin
{
	public static class OOXMLHelper
	{
		public static void ValidateOfficeFile(string fileType, MemoryStream memoryStream)
		{
			// Validate the file by trying to open it.
			// Exception is thrown if it is not valid.
			switch (fileType)
			{
				// Each Office file type has its own *Document class in the OOXML SDK.
				case "Excel":
					using (var spreadsheet = SpreadsheetDocument.Open(memoryStream, true)) { }
					break;
				case "Word":
					using (var doc = WordprocessingDocument.Open(memoryStream, true)) { }
					break;
				case "PowerPoint":
					using (var slidedeck = PresentationDocument.Open(memoryStream, true)) { }
					break;
				default:
					throw new Exception("Only Excel, Word, and PowerPoint files can be validated.");
			}
		}

		/*
         * Except for code enclosed in "CUSTOM MODIFICATION", all code and comments below this point 
         * were generated by the Open XML SDK 2.5 Productivity Tool which you can get from here:
         * https://www.microsoft.com/en-us/download/details.aspx?id=30425
         */

		// Adds child parts and generates content of the specified part.
		public static void CreateWebExTaskpanesPart(WebExTaskpanesPart part, string guid, string version)
		{
			WebExtensionPart webExtensionPart1 = part.AddNewPart<WebExtensionPart>("rId1");
			GenerateWebExtensionPart1Content(webExtensionPart1, guid,version);

			GeneratePartContent(part);
		}

		// Generates content of webExtensionPart1.
		private static void GenerateWebExtensionPart1Content(WebExtensionPart webExtensionPart1, string guid, string version)
		{
			We.WebExtension webExtension1 = new We.WebExtension() { Id = guid };
			webExtension1.AddNamespaceDeclaration("we", "http://schemas.microsoft.com/office/webextensions/webextension/2010/11");
			We.WebExtensionStoreReference webExtensionStoreReference1 = new We.WebExtensionStoreReference() { Id = guid, Version = "1.6.107.0", Store = "EXCatalog", StoreType = "EXCatalog" };
			We.WebExtensionReferenceList webExtensionReferenceList1 = new We.WebExtensionReferenceList();

			We.WebExtensionPropertyBag webExtensionPropertyBag1 = new We.WebExtensionPropertyBag();

			// Add the property that makes the taskpane visible.
			We.WebExtensionProperty webExtensionProperty1 = new We.WebExtensionProperty() { Name = "Office.AutoShowTaskpaneWithDocument", Value = "true" };
			webExtensionPropertyBag1.Append(webExtensionProperty1);

			// CUSTOM MODIFICATION BEGIN
			// Add the property that specifies the snippet to import.
			//string snippetToImportValue = string.Format("{{\"type\":\"gist\",\"id\":\"{0}\"}}", snippetID);
			//We.WebExtensionProperty webExtensionProperty2 = new We.WebExtensionProperty() { Name = "SnippetToImport", Value = snippetToImportValue };
			//webExtensionPropertyBag1.Append(webExtensionProperty2);
			// CUSTOM MODIFICATION END

			We.WebExtensionBindingList webExtensionBindingList1 = new We.WebExtensionBindingList();

			We.Snapshot snapshot1 = new We.Snapshot();
			snapshot1.AddNamespaceDeclaration("r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships");

			webExtension1.Append(webExtensionStoreReference1);
			webExtension1.Append(webExtensionReferenceList1);
			webExtension1.Append(webExtensionPropertyBag1);
			webExtension1.Append(webExtensionBindingList1);
			webExtension1.Append(snapshot1);

			webExtensionPart1.WebExtension = webExtension1;
		}

		// Generates content of part.
		private static void GeneratePartContent(WebExTaskpanesPart part)
		{
			Wetp.Taskpanes taskpanes1 = new Wetp.Taskpanes();
			taskpanes1.AddNamespaceDeclaration("wetp", "http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11");

			Wetp.WebExtensionTaskpane webExtensionTaskpane1 = new Wetp.WebExtensionTaskpane() { DockState = "right", Visibility = true, Width = 350D, Row = (UInt32Value)4U };

			Wetp.WebExtensionPartReference webExtensionPartReference1 = new Wetp.WebExtensionPartReference() { Id = "rId1" };
			webExtensionPartReference1.AddNamespaceDeclaration("r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships");

			webExtensionTaskpane1.Append(webExtensionPartReference1);

			taskpanes1.Append(webExtensionTaskpane1);

			part.Taskpanes = taskpanes1;
		}
	}
}